[workspace]
authors = ["Ezra Brooks <ezra@brooks.cx>"]
channels = ["conda-forge", "robostack-humble"]
name = "urdfz"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
test = "pytest **/*_test.py"
lint = "ruff format && ruff check && ty check"

[dependencies]
ros-humble-ament-index-python = ">=1.4.0,<2"
typer = ">=0.16.0,<0.17"
pytest = ">=8.4.1,<9"
ruff = ">=0.12.8,<0.13"
jedi = ">=0.19.2,<0.20"
python-lsp-server = ">=1.13.0,<2"
jedi-language-server = ">=0.45.1,<0.46"

[pypi-dependencies]
ty = ">=0.0.1a17, <0.0.1a18"
