[workspace]
authors = ["Ezra Brooks <ezra@brooks.cx>"]
channels = ["conda-forge", "robostack-humble"]
name = "urdfz"
platforms = ["win-64", "linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]
test = "pytest **/*_test.py"
lint = "ruff format --check && ruff check && basedpyright ."

[dependencies]
ros-humble-ament-index-python = ">=1.4.0,<2"
typer = ">=0.16.0,<0.17"
pytest = ">=8.4.1,<9"
ruff = ">=0.12.8,<0.13"
ros-humble-turtlebot3-description = ">=2.3.1,<3"
basedpyright = ">=1.32.1,<2"

[pypi-dependencies]
build = ">=1.3.0, <2"
