[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "urdfz"
version = "0.1.0"
authors = [
    {name = "Ezra Brooks", email = "ezra@brooks.cx"},
]
description = "Self-contained, portable, actually UNIFIED Robot Description Files (URDFs)"
dependencies = [
    "typer>=0.16.0,<0.17",
]

[project.scripts]
urdfz = "urdfz.__main__:main"
