name: CD

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: PyPI
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.2
        with:
          pixi-version: v0.58.0
          cache: true

      - name: Build package
        run: pixi run python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
